import member1 from "../assets/Member1.svg";
import member2 from "../assets/Member2.svg";
import member3 from "../assets/Member3.svg";
import member4 from "../assets/Member4.svg";

export const teamMembers = [
  {
    registrationId: "1",
    type: "user",
    password: "user123",
    name: "HON. DR. NADEESH PERERA",
    position: "CEO at Training Authority",
    location: "Sri Lanka",
    image: member1,
    email: "nadeesh@example.com",
    phone: "+94 123 456 789",
    duration1: "2019 - Present",
    duration2: "2020 - Present",
    companyName1: "Senior Engineer - ABC Company",
    companyName2: "Engineer - ABC Company",
    education: "BEng.(Hons) Civil Engineering - University of Moratuwa",
    engineeringProjects: "Construction Project 01 - Colombo",
  },
  {
    registrationId: "2",
    type: "user",
    password: "user123",
    name: "HON. DR. NADEESH PERERA",
    position: "CEO at Training Authority",
    location: "Sri Lanka",
    image:"./Member2.svg",
    email: "nadeesh@example.com",
    phone: "+94 123 456 789",
    duration1: "2019 - Present",
    duration2: "2020 - Present",
    companyName1: "Senior Engineer - ABC Company",
    companyName2: "Engineer - ABC Company",
    education: "BEng.(Hons) Civil Engineering - University of Moratuwa",
    engineeringProjects: "Construction Project 01 - Colombo",
  },
  {
    registrationId: "3",
    type: "guest-user",
    password: "guest123",
    name: "HON. DR. NADEESH PERERA",
    position: "CEO at Training Authority",
    location: "Sri Lanka",
    image:"./Member3.svg",
    email: "nadeesh@example.com",
    phone: "+94 123 456 789",
    duration1: "2019 - Present",
    duration2: "2020 - Present",
    companyName1: "Senior Engineer - ABC Company",
    companyName2: "Engineer - ABC Company",
    education: "BEng.(Hons) Civil Engineering - University of Moratuwa",
    engineeringProjects: "Construction Project 01 - Colombo",
  },
  {
    registrationId: "4",
    type: "guest-user",
    password: "guest123",
    name: "HON. DR. NADEESH PERERA",
    position: "CEO at Training Authority",
    location: "Sri Lanka",
    image: "./Member4.svg",
    email: "nadeesh@example.com",
    phone: "+94 123 456 789",
    duration1: "2019 - Present",
    duration2: "2020 - Present",
    companyName1: "Senior Engineer - ABC Company",
    companyName2: "Engineer - ABC Company",
    education: "BEng.(Hons) Civil Engineering - University of Moratuwa",
    engineeringProjects: "Construction Project 01 - Colombo",
  },
  {
    registrationId: "5",
    type: "user",
    password: "user123",
    name: "HON. DR. NADEESH PERERA",
    position: "CEO at Training Authority",
    location: "Sri Lanka",
    image: member2,
    email: "nadeesh@example.com",
    phone: "+94 123 456 789",
    duration1: "2019 - Present",
    duration2: "2020 - Present",
    companyName1: "Senior Engineer - ABC Company",
    companyName2: "Engineer - ABC Company",
    education: "BEng.(Hons) Civil Engineering - University of Moratuwa",
    engineeringProjects: "Construction Project 01 - Colombo",
  },
  {
    registrationId: "6",
    type: "user",
    password: "user123",
    name: "HON. DR. NADEESH PERERA",
    position: "CEO at Training Authority",
    location: "Sri Lanka",
    image: member3,
    email: "nadeesh@example.com",
    phone: "+94 123 456 789",
    duration1: "2019 - Present",
    duration2: "2020 - Present",
    companyName1: "Senior Engineer - ABC Company",
    companyName2: "Engineer - ABC Company",
    education: "BEng.(Hons) Civil Engineering - University of Moratuwa",
    engineeringProjects: "Construction Project 01 - Colombo",
  },
  {
    registrationId: "7",
    type: "guest-user",
    password: "guest123",
    name: "HON. DR. NADEESH PERERA",
    position: "CEO at Training Authority",
    location: "Sri Lanka",
    image: member4,
    email: "nadeesh@example.com",
    phone: "+94 123 456 789",
    duration1: "2019 - Present",
    duration2: "2020 - Present",
    companyName1: "Senior Engineer - ABC Company",
    companyName2: "Engineer - ABC Company",
    education: "BEng.(Hons) Civil Engineering - University of Moratuwa",
    engineeringProjects: "Construction Project 01 - Colombo",
  },
];
