/* eslint-disable react-refresh/only-export-components */
/* eslint-disable react/prop-types */
import { createContext, useContext, useState } from 'react';

const users = [
    {
      idNo: "123456",
      name: "H.W.U.V Karunarthne",
      emailAddress: "Shehahan@123.gmail.com",
      nicNo: "200182768902",
      date: "2024/12/12",
      nameWithInitials: "Mr. H.W.U.V Karunarthne",
      nameDenoted: "Heshan Wijethunge",
      gender: "Male",
      dob: "2001/08/27",
      passport: "N7825661",
      mobile: "+94 712556677",
      homeTel: "+94 812266778",
      officeTel: "+94 812266779",
      homeFax: "+94 812266780",
      officeFax: "+94 812266781",
      workplace: "LMC Makubura",
      designation: "Software Engineer",
      currentAddress: {
        line1: "11/2, Madawala Road",
        line2: "Katugasthota",
        city: "Kandy",
        province: "Central",
        country: "Sri Lanka",
      },
      officialAddress: {
        line1: "45, Temple Road",
        line2: "Maligawatta",
        city: "Colombo",
        province: "Western",
        country: "Sri Lanka",
      },
      permanentAddress: {
        line1: "72/1, Lake Road",
        line2: "Kurunegala",
        city: "Kurunegala",
        province: "North Western",
        country: "Sri Lanka",
      },
    },
    {
      idNo: "123892",
      name: "H.I.U.V Wijethunge",
      emailAddress: "malsh@123.gmail.com",
      nicNo: "200181768902",
      date: "2024/12/12",
      nameWithInitials: "Mr. H.I.U.V Wijethunge",
      nameDenoted: "Heshan Wijethunge",
      gender: "Male",
      dob: "2001/08/17",
      passport: "N7825661",
      mobile: "+94 712556677",
      homeTel: "+94 812266778",
      officeTel: "+94 812266779",
      homeFax: "+94 812266780",
      officeFax: "+94 812266781",
      workplace: "LMC Makubura",
      designation: "Software Engineer",
      currentAddress: {
        line1: "11/2, Madawala Road",
        line2: "Katugasthota",
        city: "Kandy",
        province: "Central",
        country: "Sri Lanka",
      },
      officialAddress: {
        line1: "45, Temple Road",
        line2: "Maligawatta",
        city: "Colombo",
        province: "Western",
        country: "Sri Lanka",
      },
      permanentAddress: {
        line1: "72/1, Lake Road",
        line2: "Kurunegala",
        city: "Kurunegala",
        province: "North Western",
        country: "Sri Lanka",
      },
    },
    {
      idNo: "123432",
      name: "U.V Malshi",
      emailAddress: "abc@123.gmail.com",
      nicNo: "200180768902",
      date: "2024/12/12",
      nameWithInitials: "Mr. U.V Malshi",
      nameDenoted: "Heshan Wijethunge",
      gender: "Male",
      dob: "2001/08/07",
      passport: "N7825661",
      mobile: "+94 712556677",
      homeTel: "+94 812266778",
      officeTel: "+94 812266779",
      homeFax: "+94 812266780",
      officeFax: "+94 812266781",
      workplace: "LMC Makubura",
      designation: "Software Engineer",
      currentAddress: {
        line1: "11/2, Madawala Road",
        line2: "Katugasthota",
        city: "Kandy",
        province: "Central",
        country: "Sri Lanka",
      },
      officialAddress: {
        line1: "45, Temple Road",
        line2: "Maligawatta",
        city: "Colombo",
        province: "Western",
        country: "Sri Lanka",
      },
      permanentAddress: {
        line1: "72/1, Lake Road",
        line2: "Kurunegala",
        city: "Kurunegala",
        province: "North Western",
        country: "Sri Lanka",
      },
    },
    {
      idNo: "123908",
      name: "H. Ramanyaka",
      emailAddress: "yohan@123.gmail.com",
      nicNo: "200181768902",
      date: "2024/12/12",
      nameWithInitials: "Mr. H. Ramanyaka",
      nameDenoted: "Heshan Wijethunge",
      gender: "Male",
      dob: "2001/08/17",
      passport: "N7825661",
      mobile: "+94 712556677",
      homeTel: "+94 812266778",
      officeTel: "+94 812266779",
      homeFax: "+94 812266780",
      officeFax: "+94 812266781",
      workplace: "LMC Makubura",
      designation: "Software Engineer",
      currentAddress: {
        line1: "11/2, Madawala Road",
        line2: "Katugasthota",
        city: "Kandy",
        province: "Central",
        country: "Sri Lanka",
      },
      officialAddress: {
        line1: "45, Temple Road",
        line2: "Maligawatta",
        city: "Colombo",
        province: "Western",
        country: "Sri Lanka",
      },
      permanentAddress: {
        line1: "72/1, Lake Road",
        line2: "Kurunegala",
        city: "Kurunegala",
        province: "North Western",
        country: "Sri Lanka",
      },
    },
    {
      idNo: "123456",
      name: "H.W.U.V Karunarthne",
      emailAddress: "Shehahan@123.gmail.com",
      nicNo: "200181768902",
      date: "2024/12/12",
      nameWithInitials: "Mr. H.W.U.V Karunarthne",
      nameDenoted: "Heshan Wijethunge",
      gender: "Male",
      dob: "2001/08/17",
      passport: "N7825661",
      mobile: "+94 712556677",
      homeTel: "+94 812266778",
      officeTel: "+94 812266779",
      homeFax: "+94 812266780",
      officeFax: "+94 812266781",
      workplace: "LMC Makubura",
      designation: "Software Engineer",
      currentAddress: {
        line1: "11/2, Madawala Road",
        line2: "Katugasthota",
        city: "Kandy",
        province: "Central",
        country: "Sri Lanka",
      },
      officialAddress: {
        line1: "45, Temple Road",
        line2: "Maligawatta",
        city: "Colombo",
        province: "Western",
        country: "Sri Lanka",
      },
      permanentAddress: {
        line1: "72/1, Lake Road",
        line2: "Kurunegala",
        city: "Kurunegala",
        province: "North Western",
        country: "Sri Lanka",
      },
    },
    {
      idNo: "123892",
      name: "H.I.U.V Wijethunge",
      emailAddress: "malsh@123.gmail.com",
      nicNo: "200180768902",
      date: "2024/12/12",
      nameWithInitials: "Mr. H.I.U.V Wijethunge",
      nameDenoted: "Heshan Wijethunge",
      gender: "Male",
      dob: "2001/08/07",
      passport: "N7825661",
      mobile: "+94 712556677",
      homeTel: "+94 812266778",
      officeTel: "+94 812266779",
      homeFax: "+94 812266780",
      officeFax: "+94 812266781",
      workplace: "LMC Makubura",
      designation: "Software Engineer",
      currentAddress: {
        line1: "11/2, Madawala Road",
        line2: "Katugasthota",
        city: "Kandy",
        province: "Central",
        country: "Sri Lanka",
      },
      officialAddress: {
        line1: "45, Temple Road",
        line2: "Maligawatta",
        city: "Colombo",
        province: "Western",
        country: "Sri Lanka",
      },
      permanentAddress: {
        line1: "72/1, Lake Road",
        line2: "Kurunegala",
        city: "Kurunegala",
        province: "North Western",
        country: "Sri Lanka",
      },
    },
    {
      idNo: "123432",
      name: "U.V Malshi",
      emailAddress: "abc@123.gmail.com",
      nicNo: "200180768902",
      date: "2024/12/12",
      nameWithInitials: "Mr. U.V Malshi",
      nameDenoted: "Heshan Wijethunge",
      gender: "Male",
      dob: "2001/08/07",
      passport: "N7825661",
      mobile: "+94 712556677",
      homeTel: "+94 812266778",
      officeTel: "+94 812266779",
      homeFax: "+94 812266780",
      officeFax: "+94 812266781",
      workplace: "LMC Makubura",
      designation: "Software Engineer",
      currentAddress: {
        line1: "11/2, Madawala Road",
        line2: "Katugasthota",
        city: "Kandy",
        province: "Central",
        country: "Sri Lanka",
      },
      officialAddress: {
        line1: "45, Temple Road",
        line2: "Maligawatta",
        city: "Colombo",
        province: "Western",
        country: "Sri Lanka",
      },
      permanentAddress: {
        line1: "72/1, Lake Road",
        line2: "Kurunegala",
        city: "Kurunegala",
        province: "North Western",
        country: "Sri Lanka",
      },
    },
    {
      idNo: "123908",
      name: "H. Ramanyaka",
      emailAddress: "yohan@123.gmail.com",
      nicNo: "200181768902",
      date: "2024/12/12",
      nameWithInitials: "Mr. H. Ramanyaka",
      nameDenoted: "Heshan Wijethunge",
      gender: "Male",
      dob: "2001/08/17",
      passport: "N7825661",
      mobile: "+94 712556677",
      homeTel: "+94 812266778",
      officeTel: "+94 812266779",
      homeFax: "+94 812266780",
      officeFax: "+94 812266781",
      workplace: "LMC Makubura",
      designation: "Software Engineer",
      currentAddress: {
        line1: "11/2, Madawala Road",
        line2: "Katugasthota",
        city: "Kandy",
        province: "Central",
        country: "Sri Lanka",
      },
      officialAddress: {
        line1: "45, Temple Road",
        line2: "Maligawatta",
        city: "Colombo",
        province: "Western",
        country: "Sri Lanka",
      },
      permanentAddress: {
        line1: "72/1, Lake Road",
        line2: "Kurunegala",
        city: "Kurunegala",
        province: "North Western",
        country: "Sri Lanka",
      },
    },
  ];

const UserContext = createContext();

export function UserProvider({ children }) {
  const [pendingUsers, setPendingUsers] = useState(users);
  const [registeredUsers, setRegisteredUsers] = useState([]);

  const approveUser = (user) => {
    // Remove from pending users
    setPendingUsers(pendingUsers.filter(u => u.idNo !== user.idNo));
    // Add to registered users
    setRegisteredUsers([...registeredUsers, user]);
  };

  return (
    <UserContext.Provider value={{ pendingUsers, registeredUsers, approveUser }}>
      {children}
    </UserContext.Provider>
  );
}

export const useUserContext = () => useContext(UserContext);